# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200308_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('AMD CPU', 'AMD CPU'), ('Intel CPU', 'Intel CPU'), ('AMD graphics cards', 'AMD graphics cards'), ('Nvidia graphics cards', 'Nvidia graphics cards'), ('Motherboard', 'Motherboard'), ('Storage', 'Storage')], default='product type', max_length=30),
        ),
    ]
