# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200309_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('AMD_CPU', 'AMD CPU'), ('Intel_CPU', 'Intel CPU'), ('AMD_graphic_cards', 'AMD graphic cards'), ('Nvidia_graphic_cards', 'Nvidia graphic cards'), ('Motherboard', 'Motherboard'), ('Storage', 'Storage')], default='product type', max_length=30),
        ),
    ]
